pipeline {
    agent {
        docker {
            image 'node:18.12'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm config rm proxy'
                sh 'npm config rm https-proxy --tried removing npm proxy'
                sh 'ls -lah'
                sh 'chown 118:124 -Rf /'
                sh 'npm install --loglevel=verbose'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
